#!/bin/bash		
 		
 cd $HYPER_HOME/published/DHDL		
 		
 argsArray=( "$@" )		
 sbtArgs=${argsArray[@]:0:$#}		
 
 cp $FORGE_HOME/apps/DHDL/src/* apps/src/
 sbt compile

## TODO: Enable DSE here
 echo "bin/delitec ${1}Compiler $sbtArgs"		
 bin/delitec ${1}Compiler 2>&1 | tee compile.log
