#!/bin/bash		
 		
 cd $HYPER_HOME/published/DHDL		
 		
 argsArray=( "$@" )		
 sbtArgs=${argsArray[@]:0:$#}		
 		
 echo "bin/delitec ${1}Compiler $sbtArgs"		
 bin/delitec ${1}Compiler 2>&1 | tee compile.log		
 		
 bin/delite ${1}Compiler 2>&1 | tee run.log
